
swagger: "2.0"
info:
  description: "APP - Jogador Web - Sistema desenvolvido ao longo da disciplina de TecWeb - UFSJ"
  version: "1.0.0"
  title: "Jogador Web"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "rhcsjdr@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v1"
tags:
- name: "jogadores"
  description: "adicionar jogadores"

  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /jogador:
    post:
      tags:
       - "jogadores"
      summary: "Adciona um novo jogador "
      operationId: "addjogador"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto de jogadores a ser adcionado no sistema"
        required: true
        schema:
          $ref: '#/definitions/Player'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Player'
  /jogador/{playerId}:
    get:
      tags:
      - "jogadores"
      summary: "Busca jogador pelo ID"
      operationId: "getPlayerById"
      produces:
      - "application/json"
      parameters:
      - name: "playerId"
        in: "path"
        description: "ID of jogador to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Sucesso"
          schema:
            $ref: "#/definitions/Player"
        400:
          description: "Not Fund ID Invalido"
        404:
          description: "Not Acess"
    put:
      tags:
      - "jogadores"
      summary: "Atualizar um jogador no sistema"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "playerId"
        in: "path"
        description: "ID that need to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "body"
        in: "body"
        description: "Updated jogador object "
        schema:
          $ref: '#/definitions/Player'
      responses:
        200:
          description: "Sucesso"
          schema:
            $ref: '#/definitions/Player'
        400:
          description: "Not Acess" 
        404:
          description: "Not Fund ID Invalido"
    delete:
      tags:
      - "jogadores"
      summary: "Remove um jogador"
      operationId: "deletejogador"
      produces:
        - "application/json"
      parameters:
      - name: "playerId"
        in: "path"
        description: "Bike ID to delete" 
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful Operation"
          schema:
            $ref: '#/definitions/Player'
        400:
          description: "Not Acess ID Invalido" 
        404:
          description: "Not Fund"

definitions:
  Player:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      sobrenome:
        type: "string"
      posicao:
        type: "string"  
      usuario:
        type: "string"
      acao:
        type: "string"  
      
      

 
 
     

